# Use latest version of node v8
FROM node:8.4.0

#create an app directory
RUN mkdir /app

#make /app as the working directory
WORKDIR /app

#expose default port of the docker to 3000
EXPOSE 3030

#runs this command when the container is created, can be overriden in the docker-compose.yml
CMD /bin/bash -c 'cd /app && npm install && npm run start-dev'